package project.client.persistence;

// Generated May 19, 2009 2:03:27 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Language generated by hbm2java
 */
public class Language implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Set<Word> words = new HashSet<Word>(0);

	public Language() {
	}

	public Language(String name) {
		this.name = name;
	}

	public Language(String name, String description, Set<Word> words) {
		this.name = name;
		this.description = description;
		this.words = words;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Word> getWords() {
		return this.words;
	}

	public void setWords(Set<Word> words) {
		this.words = words;
	}

}
