package project.client.persistence;

// Generated May 19, 2009 2:03:27 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

/**
 * MessageThread generated by hbm2java
 */
public class MessageThread implements java.io.Serializable {

	private Integer id;
	private MessageBoard messageBoard;
	private String name;
	private String url;
	private List<Message> messages = new LinkedList<Message>();

	public MessageThread() {
	}

	public MessageThread(MessageBoard messageBoard, String name) {
		this.messageBoard = messageBoard;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MessageBoard getMessageBoard() {
		return this.messageBoard;
	}

	public void setMessageBoard(MessageBoard messageBoard) {
		this.messageBoard = messageBoard;
		//messageBoard.getMessageThreads().add(this);
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public List<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

	
	public int getNumMessages () {
		return getMessages().size ();
	}
	
	/*
	public int getWordFrequency (String word) {
		int num = 0;
		Iterator<Message> i1 = getMessages().iterator();
		
		while (i1.hasNext()) {
			
				Message m = i1.next();
				Iterator<Sentence> i2 = m.getSentences().iterator();
				
				while (i2.hasNext()) {
					
					Sentence s = i2.next();
					Iterator<Word> i3 = s.getWords().iterator();
					
					while (i3.hasNext()) {
						Word w = i3.next();
						if (w.getContent().equals(word))
							num ++;
					}
				}
		}
		
		return num;		
	}
	*/
}
