package project.client.persistence;

// Generated May 19, 2009 2:03:27 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private MessageBoard messageBoard;
	private String name;
	private List<Message> messages = new LinkedList<Message>();

	public User() {
	}

	public User(MessageBoard messageBoard, String name) {
		this.messageBoard = messageBoard;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public MessageBoard getMessageBoard() {
		return this.messageBoard;
	}

	public void setMessageBoard(MessageBoard messageBoard) {
		this.messageBoard = messageBoard;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(List<Message> messages) {
		this.messages = messages;
	}

	
	public boolean equals(Object obj) {
		
		if (obj == null)
			return false;
		
		if (!(obj instanceof User)) {
			return false;
		}
		
		User other = (User) obj;
		return this.getId().equals(other.getId());
	}

	
	public int hashCode() {
		
		return 17 * this.getId();
	}

}
