package project.client.persistence;

// Generated May 19, 2009 2:03:27 AM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Word generated by hbm2java
 */
public class Word implements java.io.Serializable {

	private Integer id;
	private Language language;
	private String content;

	public Word() {
	}

	public Word(Language language, String content) {
		this.language = language;
		this.content = content;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String toString() {
		return this.getContent();
	}
}
